version: "3.9"
services:
  backend:
    build: ./item-service
    ports:
      - "8080:8080"
    # environment:
    #   - SPRING_PROFILES_ACTIVE=dev
    #   - ALGO=valor

  frontend:
    build: ./meli-item-frontend
    ports:
      - "3000:5713"
    depends_on:
      - backend
    # environment:
    #   - VITE_BACKEND_URL=http://backend:8080
